#!/usr/bin/env python
import sys
import os

relpath = lambda x: os.path.join(os.path.dirname(__file__), x)
sys.path.insert(0, relpath("src/"))

import libvcslog.commands
sys.exit(libvcslog.commands.main())
